# Generated by Django 3.2.8 on 2021-10-21 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Durus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('durus', models.FileField(upload_to='durus/')),
            ],
            options={
                'verbose_name': 'durus',
                'verbose_name_plural': 'durusus',
            },
        ),
    ]
