# Generated by Django 3.2.8 on 2021-10-23 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khutba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('khutba', models.FileField(upload_to='khutba/')),
            ],
            options={
                'verbose_name': 'khutba',
                'verbose_name_plural': 'khutba',
            },
        ),
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.IntegerField()),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.CharField(max_length=100)),
                ('adhan', models.CharField(max_length=100)),
                ('iqama', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='durus',
            options={'verbose_name': 'durus', 'verbose_name_plural': 'durus'},
        ),
    ]
