# Generated by Django 3.2.8 on 2021-10-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20211023_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fajr', models.CharField(max_length=100)),
                ('dhuhr', models.CharField(max_length=100)),
                ('asr', models.CharField(max_length=100)),
                ('maghrib', models.CharField(max_length=100)),
                ('isha', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Prayer',
        ),
    ]
