# Generated by Django 3.2.8 on 2021-10-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_auto_20211027_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amirhabarleader',
            old_name='amir_fedha_status',
            new_name='amir_habar_status',
        ),
    ]
