# Generated by Django 4.0.3 on 2022-11-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_rename_amirat_fedha_status_amirathabarleader_amirat_habar_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmiratDawaLeader',
        ),
        migrations.DeleteModel(
            name='AmiratFedhaLeader',
        ),
        migrations.DeleteModel(
            name='AmiratHabarLeader',
        ),
        migrations.DeleteModel(
            name='AmirDawaLeader',
        ),
        migrations.DeleteModel(
            name='AmirFedhaLeader',
        ),
        migrations.DeleteModel(
            name='AmirHabarLeader',
        ),
        migrations.DeleteModel(
            name='Dean',
        ),
        migrations.DeleteModel(
            name='Durus',
        ),
        migrations.DeleteModel(
            name='ImamsLeader',
        ),
        migrations.DeleteModel(
            name='KatibatLeader',
        ),
        migrations.DeleteModel(
            name='KatibuLeader',
        ),
        migrations.DeleteModel(
            name='Khutba',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='MudiratLeader',
        ),
        migrations.DeleteModel(
            name='MudirLeader',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='PrayerTimes',
        ),
    ]
