# Generated by Django 4.0.3 on 2022-11-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebApp', '0010_delete_amiratdawaleader_delete_amiratfedhaleader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq_qn01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.CharField(max_length=100, null=True)),
                ('answer_one', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faq_qn02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_two', models.CharField(max_length=100, null=True)),
                ('answer_two', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faq_qn03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_three', models.CharField(max_length=100, null=True)),
                ('answer_three', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faq_qn04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_four', models.CharField(max_length=100, null=True)),
                ('answer_one', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='frequent_ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.CharField(max_length=100, null=True)),
                ('question_two', models.CharField(max_length=100, null=True)),
                ('question_three', models.CharField(max_length=100, null=True)),
                ('question_four', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='icf_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/ % d/ % m/ % Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='icf_quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('video', models.FileField(blank=True, upload_to='photos/ % d/ % m/ % Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
