# Generated by Django 4.0.3 on 2022-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_rename_video_icf_quote_photo_remove_icf_event_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icf_event',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='icf_quote',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
